### ISSUE TITLE
Is it possible to show the graphic faster (as a placeholder?) so that the page layout doesn't change?

### ISSUE THREAD

**Issue by ThomasHelzle** [NUKnightLab/soundcite#41]
On my (local) testpage with several soundcite snippets, I get a quite delayed re-rendering/re-layout of the text when the sound snippets get loaded which is a bit ugly and irritating. 
So I wondered:
Would it be possible to have a temporary, correctly sized layout already in place right from the start, maybe using a placeholder with the same size as the play button? This could be either an empty graphic or some greyed out symbol (non-clickable).
When I think about having 20 to 50 snippets on a page, ATM that would create quite some visual unrest... ;-)

**Comment by JoeGermuska** [comment]
The lag for displaying the "graphic" is a feature, not a bug. The style changes are only applied once the sound relating to the clip has been loaded, because if it can't be loaded, presenting the player would be a frustration for users.

You could use your own CSS styles or apply Soundcite's classes for playable clips to achieve the result you're describing.
