### ISSUE TITLE
Embed code breaks in Wordpress

### ISSUE THREAD

**Issue by HunorKiraly** [NUKnightLab/soundcite#83]
The embed code I have to paste into the top of my post/page breaks every single time I edit the post/page. I use Wordpress, self-hosted. I think it's switching between the visual and the text editor that (mostly?) triggers it. 
After switching to visual, editing something, and then switching back to text I find this at the top of the post:
<script type='text/javascript' src='https://cdn.knightlab.com/libs/soundcite/latest/js/soundcite.min.js'></script>

instead of this: 
<link href='https://cdn.knightlab.com/libs/soundcite/latest/css/player.css' rel='stylesheet' type='text/css'><script type='text/javascript' src='https://cdn.knightlab.com/libs/soundcite/latest/js/soundcite.min.js'></script>

What the hell?

**Comment by JoeGermuska** [comment]
This is a known issue, which is technically to do with how Wordpress enforces various security measures.

The past solutions have been to understand those Wordpress configuration details and change them; however, we're happy to say that we have a Soundcite plugin for Wordpress, donated by @paulschreiber of FiveThirtyEight.com/ESPN. We have not yet submitted it to the WP plugin registry, but it is fully functional. You can check it out from https://github.com/NUKnightLab/soundcite-wordpress-plugin (copy the `soundcite` directory to `wp-plugins`) or wait until we get it listed.

You can also check out this plugin from INN Labs which supports all of Knight Lab's tools, including Soundcite: https://wordpress.org/plugins/storytelling-tools/  It is already installable from the registry.

**Comment by HunorKiraly** [comment]
Thank you for your prompt answer. I will certainly keep this in mind for 
our next project. I am not installing any more plugins to this site, as 
it is has too many already, and it's in the 'don't touch this, it's 
magically working' status, typical for no-budget non-profit projects.

I guess I'll keep re-pasting the code for a while.

Best regards,

Hunor Király

**Comment by JoeGermuska** [comment]
There are some other workarounds.

I should start by pointing out that in your original message, the "i find this" and "instead of this" text are the same, so I'm not 100% sure what issue you're seeing -- but as I noted, WordPress has an HTML sanitizing feature which, in many cases, will change markup in a post.

One general workaround would be to edit the theme and include the soundcite JS and CSS in the template for every page. Technically it adds some overhead, but in most cases, browsers would cache the files after loading it once.

Another possible workaround is to only edit the posts at "editor" or "administrator", which are the two Wordpress roles which have the [`unfiltered_html`](https://codex.wordpress.org/Roles_and_Capabilities#unfiltered_html) capability, or to grant that capability to other roles. Of course, if the post is edited by someone who doesn't have that capability, they may inadvertently cause the markup to be filtered, messing up the post.

**Comment by JoeGermuska** [comment]
cleaning out the open issues; we now recommend using the [SoundCite for WordPress plugin](https://wordpress.org/plugins/knight-lab-soundcite/), developed at FiveThirtyEight.com and donated to Knight Lab for ongoing maintenance.
